// Package fixedwidth scans fixed-width files and provides easy
// access to individual columns.
//
// Advance the scanner with the Scan method and check errors with
// the Err method, both from the underlying bufio.Scanner.
package fixedwidth

import (
	"bufio"
	"io"
)

type Substring func(line string) (field string)

func Field(index, width int) Substring {
	return func(line string) string {
		return line[index : index+width]
	}
}

// A Scanner reads records from a fixed-width-encode file.
type Scanner struct {
	*bufio.Scanner
}

// NewScanner returns a Scanner that reads from reader.
func NewScanner(reader io.Reader) *Scanner {
	return &Scanner{Scanner: bufio.NewScanner(reader)}
}

// Field returns the specified Substring from the most recent
// record generated by a call to Scanner.Scan as a string.
func (this *Scanner) Field(field Substring) string {
	return field(this.Text())
}

// Fields returns the specified Substrings from the most recent
// record generated by a call to Scanner.Scan as a []string.
func (this *Scanner) Fields(fields ...Substring) (values []string) {
	for _, field := range fields {
		values = append(values, this.Field(field))
	}
	return values
}
